import type { NormalizedError } from '../watchers/types.js';
import type { AnalysisResult } from '../analyzer/error-analyzer.js';
import type { FixResult } from '../fixer/code-fixer.js';

/**
 * Generate a PR title for an auto-fix.
 */
export function generatePRTitle(error: NormalizedError, analysis: AnalysisResult): string {
  // Keep it short but descriptive
  const errorType = error.errorType || 'error';
  const service = error.serviceName;

  // Truncate description if too long
  let description = analysis.suggestedFix?.description || 'Fix production error';
  if (description.length > 50) {
    description = description.substring(0, 47) + '...';
  }

  return `fix(${service}): ${description}`;
}

/**
 * Generate the PR body/description.
 */
export function generatePRBody(params: {
  error: NormalizedError;
  analysis: AnalysisResult;
  fix: FixResult;
  fingerprint: string;
}): string {
  const { error, analysis, fix, fingerprint } = params;

  let body = `## Auto-Fix: Production Error

This PR was automatically generated by the Auto-Fix Agent after detecting a production error.

### Error Details

**Service:** \`${error.serviceName}\`
**Environment:** \`${error.environmentName}\`
**First Detected:** ${error.timestamp.toISOString()}
**Error Type:** ${error.errorType || 'Unknown'}

\`\`\`
${error.message}
\`\`\`
`;

  if (error.stackTrace) {
    body += `
<details>
<summary>Stack Trace</summary>

\`\`\`
${error.stackTrace}
\`\`\`

</details>
`;
  }

  body += `
### Root Cause Analysis

${analysis.rootCause}

### Fix Description

${analysis.suggestedFix?.description || 'See file changes below.'}

**Confidence:** ${analysis.confidence}

### Files Changed

${fix.filesChanged?.map((f) => `- \`${f}\``).join('\n') || 'No files changed'}
`;

  if (analysis.testSuggestion) {
    body += `
### Testing Suggestions

${analysis.testSuggestion}
`;
  }

  body += `
### Verification Checklist

- [ ] Review the code changes
- [ ] Verify the fix addresses the root cause
- [ ] Run tests locally
- [ ] Deploy to staging and verify error is resolved
- [ ] Monitor production after merge

---

**Fingerprint:** \`${fingerprint}\`

<sub>Generated by [Infraprint Auto-Fix Agent](https://github.com/infraprint/infraprint)</sub>
`;

  return body;
}

/**
 * Generate commit message for the fix.
 */
export function generateCommitMessage(
  error: NormalizedError,
  analysis: AnalysisResult,
  fingerprint: string
): string {
  const title = analysis.suggestedFix?.description || 'Fix production error';
  const service = error.serviceName;

  return `fix(${service}): ${title}

Root cause: ${analysis.rootCause}

Auto-generated fix for production error.
Fingerprint: ${fingerprint}
Error type: ${error.errorType || 'Unknown'}
Confidence: ${analysis.confidence}
`;
}
